"""FastAPI application for the Echelonos obligation report API.

Serves obligation report data generated by the Stage 7 report module.
Currently uses demo data; in production the endpoints would query the
database for the requested organization.

Run standalone with::

    uvicorn echelonos.api.app:app --reload
"""

from __future__ import annotations

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from echelonos.api.demo_data import DEMO_DOCUMENTS, DEMO_LINKS, DEMO_OBLIGATIONS
from echelonos.stages.stage_7_report import (
    FlagItem,
    ObligationReport,
    ObligationRow,
    generate_report,
)

# ---------------------------------------------------------------------------
# Application setup
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Echelonos API",
    description="Contract obligation extraction and report API",
    version="0.1.0",
)

# CORS -- allow the React dev server and common local origins.
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------


def _get_demo_report(org_name: str) -> ObligationReport:
    """Generate a demo report for the given org name.

    In production this would fetch obligations, documents, and links from
    the database for the requested organization.  For now it always returns
    demo data with the org_name substituted into the report header.
    """
    return generate_report(
        org_name=org_name,
        obligations=DEMO_OBLIGATIONS,
        documents=DEMO_DOCUMENTS,
        links=DEMO_LINKS,
    )


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@app.get("/api/health")
def health_check() -> dict:
    """Health check endpoint."""
    return {"status": "ok", "service": "echelonos-api"}


@app.get("/api/report/{org_name}", response_model=ObligationReport)
def get_report(org_name: str) -> ObligationReport:
    """Return the full obligation report for an organization.

    Currently returns demo data for any org_name.
    """
    return _get_demo_report(org_name)


@app.get("/api/report/{org_name}/obligations", response_model=list[ObligationRow])
def get_obligations(org_name: str) -> list[ObligationRow]:
    """Return just the obligation matrix rows for an organization."""
    report = _get_demo_report(org_name)
    return report.obligations


@app.get("/api/report/{org_name}/flags", response_model=list[FlagItem])
def get_flags(org_name: str) -> list[FlagItem]:
    """Return just the flag report for an organization."""
    report = _get_demo_report(org_name)
    return report.flags


@app.get("/api/report/{org_name}/summary")
def get_summary(org_name: str) -> dict:
    """Return just the summary statistics for an organization."""
    report = _get_demo_report(org_name)
    return report.summary
