import type { ObligationReport } from './types';

export const mockReport: ObligationReport = {
  org_name: 'Acme Corp',
  generated_at: new Date().toISOString(),
  total_obligations: 24,
  active_obligations: 16,
  superseded_obligations: 5,
  unresolved_obligations: 3,
  obligations: [
    {
      number: 1,
      obligation_text: 'Vendor shall deliver monthly performance reports by the 5th business day of each calendar month.',
      obligation_type: 'Delivery',
      responsible_party: 'Vendor',
      counterparty: 'Acme Corp',
      source: 'MSA-2024-001, Section 4.2',
      status: 'ACTIVE',
      frequency: 'Monthly',
      deadline: '5th business day',
      confidence: 0.95,
      source_clause: 'Section 4.2: The Vendor shall prepare and deliver to the Client a comprehensive performance report no later than the fifth (5th) business day of each calendar month.',
      source_page: 12,
      doc_filename: 'MSA-2024-001.pdf',
    },
    {
      number: 2,
      obligation_text: 'Client shall pay all undisputed invoices within 30 days of receipt.',
      obligation_type: 'Financial',
      responsible_party: 'Acme Corp',
      counterparty: 'Vendor',
      source: 'MSA-2024-001, Section 7.1',
      status: 'ACTIVE',
      frequency: 'Per invoice',
      deadline: '30 days',
      confidence: 0.98,
      source_clause: 'Section 7.1: The Client agrees to pay all undisputed invoices within thirty (30) calendar days from the date of receipt of a valid invoice.',
      source_page: 18,
      doc_filename: 'MSA-2024-001.pdf',
    },
    {
      number: 3,
      obligation_text: 'Vendor shall maintain 99.9% uptime SLA for all production systems.',
      obligation_type: 'SLA',
      responsible_party: 'Vendor',
      counterparty: 'Acme Corp',
      source: 'SOW-2024-003, Section 3.1',
      status: 'ACTIVE',
      frequency: 'Continuous',
      deadline: null,
      confidence: 0.97,
      source_clause: 'Section 3.1: The Vendor guarantees a minimum uptime of 99.9% measured on a monthly basis for all production-grade systems.',
      source_page: 5,
      doc_filename: 'SOW-2024-003.pdf',
    },
    {
      number: 4,
      obligation_text: 'Both parties shall maintain confidentiality of proprietary information for a period of 5 years.',
      obligation_type: 'Confidentiality',
      responsible_party: 'Both Parties',
      counterparty: 'Both Parties',
      source: 'NDA-2024-001, Section 2.1',
      status: 'ACTIVE',
      frequency: null,
      deadline: '5 years',
      confidence: 0.93,
      source_clause: 'Section 2.1: Each party agrees to maintain in strict confidence all Proprietary Information disclosed by the other party for a period of five (5) years from the date of disclosure.',
      source_page: 2,
      doc_filename: 'NDA-2024-001.pdf',
    },
    {
      number: 5,
      obligation_text: 'Vendor shall provide quarterly security audit reports.',
      obligation_type: 'Compliance',
      responsible_party: 'Vendor',
      counterparty: 'Acme Corp',
      source: 'MSA-2024-001, Section 9.3',
      status: 'ACTIVE',
      frequency: 'Quarterly',
      deadline: 'End of quarter',
      confidence: 0.91,
      source_clause: 'Section 9.3: The Vendor shall conduct and provide quarterly security audit reports in compliance with SOC 2 Type II standards.',
      source_page: 24,
      doc_filename: 'MSA-2024-001.pdf',
    },
    {
      number: 6,
      obligation_text: 'Client shall provide access to necessary systems within 5 business days of onboarding request.',
      obligation_type: 'Delivery',
      responsible_party: 'Acme Corp',
      counterparty: 'Vendor',
      source: 'SOW-2024-003, Section 5.2',
      status: 'ACTIVE',
      frequency: 'As needed',
      deadline: '5 business days',
      confidence: 0.88,
      source_clause: 'Section 5.2: The Client shall ensure that system access credentials and necessary permissions are provisioned within five (5) business days of receiving a formal onboarding request.',
      source_page: 9,
      doc_filename: 'SOW-2024-003.pdf',
    },
    {
      number: 7,
      obligation_text: 'Vendor shall maintain $5M professional liability insurance coverage.',
      obligation_type: 'Insurance',
      responsible_party: 'Vendor',
      counterparty: 'Acme Corp',
      source: 'MSA-2024-001, Section 11.1',
      status: 'ACTIVE',
      frequency: 'Annual renewal',
      deadline: null,
      confidence: 0.96,
      source_clause: 'Section 11.1: The Vendor shall maintain professional liability insurance with a minimum coverage of Five Million US Dollars ($5,000,000).',
      source_page: 28,
      doc_filename: 'MSA-2024-001.pdf',
    },
    {
      number: 8,
      obligation_text: 'Vendor shall respond to critical incidents within 1 hour.',
      obligation_type: 'SLA',
      responsible_party: 'Vendor',
      counterparty: 'Acme Corp',
      source: 'SOW-2024-003, Section 3.4',
      status: 'ACTIVE',
      frequency: 'Per incident',
      deadline: '1 hour',
      confidence: 0.94,
      source_clause: 'Section 3.4: For Severity 1 (Critical) incidents, the Vendor shall acknowledge and begin response within one (1) hour of notification.',
      source_page: 7,
      doc_filename: 'SOW-2024-003.pdf',
    },
    {
      number: 9,
      obligation_text: 'Vendor shall provide 60 days written notice prior to any material changes to the service.',
      obligation_type: 'Notification',
      responsible_party: 'Vendor',
      counterparty: 'Acme Corp',
      source: 'MSA-2024-001, Section 12.2',
      status: 'ACTIVE',
      frequency: 'As needed',
      deadline: '60 days prior',
      confidence: 0.92,
      source_clause: 'Section 12.2: The Vendor shall provide no less than sixty (60) calendar days prior written notice of any material change to the services.',
      source_page: 30,
      doc_filename: 'MSA-2024-001.pdf',
    },
    {
      number: 10,
      obligation_text: 'Client shall designate a primary point of contact within 10 business days of contract execution.',
      obligation_type: 'Governance',
      responsible_party: 'Acme Corp',
      counterparty: 'Vendor',
      source: 'MSA-2024-001, Section 5.1',
      status: 'ACTIVE',
      frequency: 'One-time',
      deadline: '10 business days',
      confidence: 0.89,
      source_clause: 'Section 5.1: The Client shall appoint and communicate a designated primary point of contact within ten (10) business days.',
      source_page: 14,
      doc_filename: 'MSA-2024-001.pdf',
    },
    {
      number: 11,
      obligation_text: 'Vendor shall complete data migration within 90 days of project kickoff.',
      obligation_type: 'Delivery',
      responsible_party: 'Vendor',
      counterparty: 'Acme Corp',
      source: 'SOW-2024-003, Section 2.3',
      status: 'ACTIVE',
      frequency: 'One-time',
      deadline: '90 days',
      confidence: 0.87,
      source_clause: 'Section 2.3: The Vendor shall complete all data migration activities within ninety (90) calendar days from the official project kickoff date.',
      source_page: 4,
      doc_filename: 'SOW-2024-003.pdf',
    },
    {
      number: 12,
      obligation_text: 'Vendor shall provide training for up to 50 users at no additional cost.',
      obligation_type: 'Delivery',
      responsible_party: 'Vendor',
      counterparty: 'Acme Corp',
      source: 'SOW-2024-003, Section 6.1',
      status: 'ACTIVE',
      frequency: 'One-time',
      deadline: 'Prior to go-live',
      confidence: 0.90,
      source_clause: 'Section 6.1: The Vendor shall conduct training sessions for up to fifty (50) designated Client personnel at no additional charge.',
      source_page: 11,
      doc_filename: 'SOW-2024-003.pdf',
    },
    {
      number: 13,
      obligation_text: 'Client shall pay a late fee of 1.5% per month on overdue invoices.',
      obligation_type: 'Financial',
      responsible_party: 'Acme Corp',
      counterparty: 'Vendor',
      source: 'MSA-2024-001, Section 7.3',
      status: 'ACTIVE',
      frequency: 'Per overdue invoice',
      deadline: null,
      confidence: 0.94,
      source_clause: 'Section 7.3: A late payment fee of one and one-half percent (1.5%) per month shall be applied to all undisputed invoices not paid within the payment term.',
      source_page: 19,
      doc_filename: 'MSA-2024-001.pdf',
    },
    {
      number: 14,
      obligation_text: 'Vendor shall back up all client data daily with 30-day retention.',
      obligation_type: 'SLA',
      responsible_party: 'Vendor',
      counterparty: 'Acme Corp',
      source: 'SOW-2024-003, Section 3.6',
      status: 'ACTIVE',
      frequency: 'Daily',
      deadline: null,
      confidence: 0.96,
      source_clause: 'Section 3.6: The Vendor shall perform daily backups of all Client data with a minimum retention period of thirty (30) days.',
      source_page: 8,
      doc_filename: 'SOW-2024-003.pdf',
    },
    {
      number: 15,
      obligation_text: 'Vendor shall provide source code escrow in the event of bankruptcy or cessation of business.',
      obligation_type: 'IP',
      responsible_party: 'Vendor',
      counterparty: 'Acme Corp',
      source: 'MSA-2024-001, Section 14.1',
      status: 'ACTIVE',
      frequency: null,
      deadline: null,
      confidence: 0.85,
      source_clause: 'Section 14.1: In the event the Vendor ceases business operations, all source code shall be released from escrow to the Client.',
      source_page: 33,
      doc_filename: 'MSA-2024-001.pdf',
    },
    {
      number: 16,
      obligation_text: 'Vendor shall comply with GDPR and CCPA for all data processing activities.',
      obligation_type: 'Compliance',
      responsible_party: 'Vendor',
      counterparty: 'Acme Corp',
      source: 'MSA-2024-001, Section 10.2',
      status: 'ACTIVE',
      frequency: 'Continuous',
      deadline: null,
      confidence: 0.97,
      source_clause: 'Section 10.2: The Vendor shall ensure full compliance with the General Data Protection Regulation (GDPR) and the California Consumer Privacy Act (CCPA).',
      source_page: 26,
      doc_filename: 'MSA-2024-001.pdf',
    },
    {
      number: 17,
      obligation_text: 'Previous payment terms of Net 45 are superseded by the amended Net 30 terms.',
      obligation_type: 'Financial',
      responsible_party: 'Acme Corp',
      counterparty: 'Vendor',
      source: 'Amendment-2024-001, Section 1.1',
      status: 'SUPERSEDED',
      frequency: 'Per invoice',
      deadline: 'Net 45 (superseded)',
      confidence: 0.92,
      source_clause: 'Section 1.1: The payment terms set forth in Section 7.1 of the MSA are hereby amended from Net 45 to Net 30.',
      source_page: 1,
      doc_filename: 'Amendment-2024-001.pdf',
      amendment_history: [
        {
          amendment_obligation_text: 'Client shall pay all undisputed invoices within 30 days of receipt.',
          amendment_source_clause: 'Section 1.1: The payment terms set forth in Section 7.1 of the MSA are hereby amended from Net 45 to Net 30.',
          action: 'REPLACE',
          reasoning: 'The amendment entirely replaces the payment term from Net 45 to Net 30, superseding the original clause.',
          confidence: 0.92,
          doc_id: 'doc-amendment-001',
          doc_filename: 'Amendment-2024-001.pdf',
          amendment_number: 1,
        },
      ],
    },
    {
      number: 18,
      obligation_text: 'Original SLA of 99.5% uptime is superseded by 99.9% uptime requirement.',
      obligation_type: 'SLA',
      responsible_party: 'Vendor',
      counterparty: 'Acme Corp',
      source: 'Amendment-2024-002, Section 2.1',
      status: 'SUPERSEDED',
      frequency: 'Continuous',
      deadline: null,
      confidence: 0.91,
      source_clause: 'Section 2.1: The uptime guarantee in SOW Section 3.1 is hereby increased from 99.5% to 99.9% effective immediately.',
      source_page: 1,
      doc_filename: 'Amendment-2024-002.pdf',
      amendment_history: [
        {
          amendment_obligation_text: 'Vendor shall maintain 99.9% uptime SLA for all production systems.',
          amendment_source_clause: 'Section 2.1: The uptime guarantee in SOW Section 3.1 is hereby increased from 99.5% to 99.9% effective immediately.',
          action: 'REPLACE',
          reasoning: 'The amendment increases the uptime SLA from 99.5% to 99.9%, completely replacing the original requirement.',
          confidence: 0.91,
          doc_id: 'doc-amendment-002',
          doc_filename: 'Amendment-2024-002.pdf',
          amendment_number: 2,
        },
      ],
    },
    {
      number: 19,
      obligation_text: 'Previous incident response time of 4 hours is superseded by 1 hour requirement.',
      obligation_type: 'SLA',
      responsible_party: 'Vendor',
      counterparty: 'Acme Corp',
      source: 'Amendment-2024-002, Section 2.3',
      status: 'SUPERSEDED',
      frequency: 'Per incident',
      deadline: '4 hours (superseded)',
      confidence: 0.89,
      source_clause: 'Section 2.3: The critical incident response time is amended from four (4) hours to one (1) hour.',
      source_page: 2,
      doc_filename: 'Amendment-2024-002.pdf',
      amendment_history: [
        {
          amendment_obligation_text: 'Vendor shall respond to critical incidents within 1 hour.',
          amendment_source_clause: 'Section 2.3: The critical incident response time is amended from four (4) hours to one (1) hour.',
          action: 'MODIFY',
          reasoning: 'The amendment modifies the incident response time from 4 hours to 1 hour, tightening the SLA requirement.',
          confidence: 0.89,
          doc_id: 'doc-amendment-002',
          doc_filename: 'Amendment-2024-002.pdf',
          amendment_number: 2,
        },
      ],
    },
    {
      number: 20,
      obligation_text: 'Original training obligation for 25 users superseded by 50 user requirement.',
      obligation_type: 'Delivery',
      responsible_party: 'Vendor',
      counterparty: 'Acme Corp',
      source: 'Addendum-2024-001, Section 3.1',
      status: 'SUPERSEDED',
      frequency: 'One-time',
      deadline: 'Prior to go-live',
      confidence: 0.86,
      source_clause: 'Section 3.1: Training capacity is expanded from twenty-five (25) users to fifty (50) users at no additional charge.',
      source_page: 2,
      doc_filename: 'Addendum-2024-001.pdf',
      amendment_history: [
        {
          amendment_obligation_text: 'Vendor shall provide training for up to 50 users at no additional cost.',
          amendment_source_clause: 'Section 3.1: Training capacity is expanded from twenty-five (25) users to fifty (50) users at no additional charge.',
          action: 'REPLACE',
          reasoning: 'The addendum replaces the original 25-user training obligation with a 50-user requirement.',
          confidence: 0.86,
          doc_id: 'doc-addendum-001',
          doc_filename: 'Addendum-2024-001.pdf',
          amendment_number: 1,
        },
      ],
    },
    {
      number: 21,
      obligation_text: 'Original backup retention of 14 days superseded by 30-day retention requirement.',
      obligation_type: 'SLA',
      responsible_party: 'Vendor',
      counterparty: 'Acme Corp',
      source: 'Amendment-2024-002, Section 2.5',
      status: 'SUPERSEDED',
      frequency: 'Daily',
      deadline: null,
      confidence: 0.88,
      source_clause: 'Section 2.5: Backup retention is extended from fourteen (14) days to thirty (30) days.',
      source_page: 3,
      doc_filename: 'Amendment-2024-002.pdf',
      amendment_history: [
        {
          amendment_obligation_text: 'Vendor shall back up all client data daily with 30-day retention.',
          amendment_source_clause: 'Section 2.5: Backup retention is extended from fourteen (14) days to thirty (30) days.',
          action: 'MODIFY',
          reasoning: 'The amendment modifies the backup retention period from 14 days to 30 days while keeping the daily backup frequency unchanged.',
          confidence: 0.88,
          doc_id: 'doc-amendment-002',
          doc_filename: 'Amendment-2024-002.pdf',
          amendment_number: 2,
        },
      ],
    },
    {
      number: 22,
      obligation_text: 'Vendor shall provide dedicated account manager (referenced in Addendum-2024-002 but document not found).',
      obligation_type: 'Governance',
      responsible_party: 'Vendor',
      counterparty: 'Acme Corp',
      source: 'Addendum-2024-002 (MISSING)',
      status: 'UNRESOLVED',
      frequency: 'Continuous',
      deadline: null,
      confidence: 0.72,
      source_clause: 'Referenced in Amendment-2024-002 Section 4.1 but source addendum not available for verification.',
      source_page: undefined,
      doc_filename: undefined,
    },
    {
      number: 23,
      obligation_text: 'Vendor penalty clause for SLA breaches (referenced but source clause is ambiguous).',
      obligation_type: 'Financial',
      responsible_party: 'Vendor',
      counterparty: 'Acme Corp',
      source: 'SOW-2024-003, Section 3.8 (AMBIGUOUS)',
      status: 'UNRESOLVED',
      frequency: 'Per breach',
      deadline: null,
      confidence: 0.65,
      source_clause: 'Section 3.8 text is partially illegible in the scanned document. Appears to reference financial penalties but exact terms cannot be confirmed.',
      source_page: 8,
      doc_filename: 'SOW-2024-003.pdf',
    },
    {
      number: 24,
      obligation_text: 'Data residency requirements for EU customer data (clause partially redacted).',
      obligation_type: 'Compliance',
      responsible_party: 'Vendor',
      counterparty: 'Acme Corp',
      source: 'MSA-2024-001, Section 10.5 (PARTIAL)',
      status: 'UNRESOLVED',
      frequency: 'Continuous',
      deadline: null,
      confidence: 0.58,
      source_clause: 'Section 10.5: [REDACTED] ... shall ensure that all personal data of EU-based [REDACTED] ... in accordance with applicable data residency [REDACTED].',
      source_page: 27,
      doc_filename: 'MSA-2024-001.pdf',
    },
  ],
  flags: [
    {
      flag_type: 'LOW_CONFIDENCE',
      severity: 'RED',
      entity_type: 'obligation',
      entity_id: 'obl-24',
      message: 'Obligation #24 has confidence score of 0.58 - source clause is partially redacted and may be incomplete.',
    },
    {
      flag_type: 'UNRESOLVED',
      severity: 'RED',
      entity_type: 'obligation',
      entity_id: 'obl-23',
      message: 'Obligation #23 references an ambiguous penalty clause in SOW-2024-003 Section 3.8 that could not be fully extracted.',
    },
    {
      flag_type: 'UNLINKED',
      severity: 'RED',
      entity_type: 'document',
      entity_id: 'doc-addendum-002',
      message: 'Addendum-2024-002 is referenced by Amendment-2024-002 but was not found in the document corpus.',
    },
    {
      flag_type: 'LOW_CONFIDENCE',
      severity: 'ORANGE',
      entity_type: 'obligation',
      entity_id: 'obl-22',
      message: 'Obligation #22 has confidence score of 0.72 - source document is missing from the corpus.',
    },
    {
      flag_type: 'AMBIGUOUS',
      severity: 'ORANGE',
      entity_type: 'obligation',
      entity_id: 'obl-15',
      message: 'Obligation #15 (source code escrow) has confidence 0.85 - escrow terms may have been modified by a later addendum.',
    },
    {
      flag_type: 'LOW_CONFIDENCE',
      severity: 'ORANGE',
      entity_type: 'obligation',
      entity_id: 'obl-20',
      message: 'Obligation #20 supersession confidence is 0.86 - training capacity change from addendum may not fully override SOW terms.',
    },
    {
      flag_type: 'UNVERIFIED',
      severity: 'YELLOW',
      entity_type: 'obligation',
      entity_id: 'obl-6',
      message: 'Obligation #6 (system access provisioning) has not been cross-verified against a second extraction model.',
    },
    {
      flag_type: 'UNVERIFIED',
      severity: 'YELLOW',
      entity_type: 'obligation',
      entity_id: 'obl-11',
      message: 'Obligation #11 (data migration timeline) has not been cross-verified. 90-day deadline may conflict with project timeline.',
    },
    {
      flag_type: 'AMBIGUOUS',
      severity: 'YELLOW',
      entity_type: 'document',
      entity_id: 'doc-amendment-002',
      message: 'Amendment-2024-002 references multiple SOW sections but linkage confidence varies between 0.86 and 0.91.',
    },
    {
      flag_type: 'UNVERIFIED',
      severity: 'WHITE',
      entity_type: 'obligation',
      entity_id: 'obl-10',
      message: 'Obligation #10 (primary contact designation) is a one-time obligation that may already be fulfilled.',
    },
    {
      flag_type: 'UNVERIFIED',
      severity: 'WHITE',
      entity_type: 'obligation',
      entity_id: 'obl-4',
      message: 'Obligation #4 (confidentiality) - standard NDA clause with high confidence but not yet verified by second model.',
    },
  ],
  summary: {
    by_type: {
      SLA: 5,
      Financial: 4,
      Delivery: 4,
      Compliance: 3,
      Confidentiality: 1,
      Insurance: 1,
      Notification: 1,
      Governance: 2,
      IP: 1,
    },
    by_status: {
      ACTIVE: 16,
      SUPERSEDED: 5,
      UNRESOLVED: 3,
    },
    by_responsible_party: {
      Vendor: 16,
      'Acme Corp': 5,
      'Both Parties': 1,
    },
  },
};
